platform :ios, '9.0'
use_frameworks!

target 'CITY' do

pod 'Firebase', '~> 4.4.0'
pod 'Firebase/Storage'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Auth'
pod 'Firebase/Performance'
pod 'GoogleMaps'
pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'

end
